if(WIN32)
	message(STATUS "Running on Windows")
elseif(UNIX)
	message(STATUS "Running on Linux")
elseif(APPLE)
	message(STATUS "Running on macOS")
else()
	message(FATAL_ERROR "Unsupported env")
endif()