name: Build and Test

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1
      with:
        cmake-version: '3.30'

    - name: Set up C++
      run: sudo apt-get install g++-10

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtest-dev sqlite3 libsqlite3-dev valgrind

    - name: Build project
      run: |
        mkdir build
        cmake -S . -B build -DCMAKE_CXX_COMPILER=g++-10 
        cd build
        make sqlighter
        make sqlighter_tests
    
    - name: Check GCC/Clang version
      run: |
        g++ --version
        clang --version
    
    - name: Run tests
      run: |
        ./build/bin/sqlighter_tests
        
    - name: Run Valgrind for memory leak check
      run: |
        valgrind --leak-check=full ./build/bin/sqlighter_tests