name: Build and Test

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1
      with:
        cmake-version: '3.30'

    - name: Set up C++
      run: |
        sudo apt-get install -y gcc-9 g++-9
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 100
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 100

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtest-dev sqlite3 libsqlite3-dev valgrind
        sudo apt install lcov
    
    - name: Check Versions
      run: |
        g++ --version
        clang --version
        valgrind --version
        lcov --version
        gcov --version

    - name: Build project
      run: |
        cmake -S . -B build
        cmake --build build --target sqlighter_tests
        
    - name: Run unit tests
      run: |
        cmake --build build --target test
        
    - name: Checking for leaks with Valgrind
      run: |
        cmake --build build --target leak_check
        
    - name: Rebuild for coverage
      run: |
        cmake --build build --target purge
        cmake -S . -B build -DBUILD_FOR_COVER=true
        
    - name: Run coverage
      run: |
        cmake --build build --target cover
      