name: Windows Build and Test

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Cygwin using cygwin-install-action
      uses: cygwin/cygwin-install-action@master
      with:
        packages: cmake,make,sqlite3

