name: Build and Test

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Cygwin
      run: |
        Invoke-WebRequest -Uri https://www.cygwin.com/setup-x86_64.exe -OutFile C:\cygwin_setup.exe
        Start-Process C:\cygwin_setup.exe -ArgumentList '/S', '/D=C:\cygwin' -Wait
        & C:\cygwin\bin\bash.exe --login -c "apt-cyg install gcc g++ make cmake sqlite3 libsqlite3-dev valgrind lcov"

    - name: Check Versions
      run: |
        & C:\cygwin\bin\bash.exe --login -c "gcc --version"
        & C:\cygwin\bin\bash.exe --login -c "g++ --version"
        & C:\cygwin\bin\bash.exe --login -c "clang --version"
        & C:\cygwin\bin\bash.exe --login -c "valgrind --version"
        & C:\cygwin\bin\bash.exe --login -c "lcov --version"
        & C:\cygwin\bin\bash.exe --login -c "gcov --version"

    - name: Build project
      run: |
        & C:\cygwin\bin\bash.exe --login -c "cmake -S . -B build/debug"
        & C:\cygwin\bin\bash.exe --login -c "cmake --build build/debug --target sqlighter"